Repository DNNCommunity/DNNDocs, pull requests merged in 2019-06, with the labels that each got.

#304 Fixed the Product-Version / Releases debacle & updated git ignore
  .gitignore
  content/administrators/releases/index.md
Labels: documentation

#305 Updated Admin TOC to reflect 'Releases' instead of 'Product Versions'
  content/administrators/toc.md
Labels: documentation

#308 Minor fix to container intro
  content/designers/creating-themes/create-container/index.md
Labels: docs-approved, docs-content-editing, docs-structural-review, documentation

#309 ACTIONBUTTON mentioned twice in the SKO table
  content/designers/creating-themes/create-container/index.md
Labels: docs-approved, docs-content-editing, docs-structural-review, documentation

#312 Append ' -- DNN Docs' to the meta title of DNN Docs pages
  templates/dnn-docs/partials/head.tmpl.partial
Labels: enhancement

#314 Resolves #310 - New icons for the docs!
  images/administrator-icon.svg
  images/designer-icon.svg
  images/developers-icon.svg
  templates/dnn-docs/index.html.tmpl
  templates/dnn-docs/styles/docfx.css
Labels: enhancement
