Repository DNNCommunity/DNNDocs, pull requests merged in 2020-03, with the labels that each got.

#438 Correct suggested upgrade path to 9.5.0
  content/getting-started/setup/upgrades/suggested-upgrade-path/index.md
Labels: documentation

#441 Improve Contribution section of Getting Started
  content/getting-started/contribution/dnn-docs/get-dnn-docs-running-locally/index.md
  content/getting-started/contribution/dnn-docs/how-to-edit-an-article-in-browser/index.md
  content/getting-started/contribution/dnn-docs/how-to-edit-an-article/index.md
  content/getting-started/contribution/dnn-docs/how-to-edit-source-code-comments/index.md
  content/getting-started/contribution/dnn-docs/how-to-submit-a-new-topic/index.md
  content/getting-started/contribution/dnn-docs/index.md
  content/getting-started/contribution/dnn-docs/markdown-guide-to-docfx/index.md
  content/getting-started/contribution/index.md
  content/getting-started/toc.md
  content/tutorials/contribute/docs/toc.md
  content/tutorials/contribute/platform/index.md
  content/tutorials/contribute/platform/toc.md
Labels: documentation

#443 Fix page title issue for How To Submit A New Topic
  content/getting-started/contribution/dnn-docs/how-to-submit-a-new-topic/index.md
Labels: documentation

#445 Update Get Involved on home page with more relevant links
  templates/dnn-docs/index.html.tmpl
Labels: documentation

#447 Update Get Started on home page with more relevant links
  templates/dnn-docs/index.html.tmpl
Labels: documentation

#454 Correct uid for content-management to follow established convention
  content/features/content-management/index.md
  content/features/index.md
  content/features/toc.md
Labels: bug, documentation

#455 Correct uid for general to follow established convention
  content/features/general/index.md
  content/features/index.md
  content/features/toc.md
Labels: bug, documentation

#456 Correct uid for extensibility to follow established convention
  content/features/extensibility/index.md
  content/features/index.md
  content/features/toc.md
Labels: bug, documentation

#457 Correct uid for security-privacy to follow established convention
  content/features/index.md
  content/features/security-privacy/index.md
  content/features/toc.md
Labels: bug, documentation

#458 Correct uid for performance to follow established convention
  content/features/index.md
  content/features/performance/index.md
  content/features/toc.md
Labels: bug, documentation

#459 Correct uid for tools-utilities to follow established convention
  content/features/index.md
  content/features/toc.md
  content/features/tools-utilities/index.md
Labels: bug, documentation

#462 Resolves issue #461
  content/tutorials/toc.md
  content/tutorials/troubleshooting/ts-too-many-redirects/index.md
Labels: documentation

#466 Added more context to the various development options
  content/features/extensibility/extensions/index.md
Labels: documentation

#470 Add DNN Platform Requirements to Getting Started section
  content/getting-started/setup/requirements/index.md
  content/tutorials/server/requirements/index.md
  content/tutorials/server/setup/administrators-setup-overview/index.md
  content/tutorials/server/setup/set-up-dnn/index.md
  content/tutorials/server/setup/set-up-iis/index.md
  content/tutorials/server/setup/set-up-sql/index.md
  content/tutorials/toc.md
Labels: documentation

#425 Create index.md
  content/features/extensibility/event-system/index.md
Labels: on hold

#473 Themes/sko/breadcrumbs
  content/tutorials/themes/theme-objects/breadcrumb/index.md
  content/tutorials/themes/theme-objects/ddrmenu/index.md
  content/tutorials/themes/theme-objects/index.md
  content/tutorials/toc.md
Labels: documentation
