Repository DNNCommunity/DNNDocs, pull requests merged in 2024-04, with the labels that each got.

#709 Update tutorials table of contents to correct typo
  content/tutorials/toc.md
Labels: bug

#710 Removes CI builds on ubuntu/osx
  .github/workflows/PR_Validation.yml
  build/Build.cs
Labels: build

#711 Resolve several formatting issues with `cssexclude`
  content/tutorials/themes/theme-objects/cssexclude/index.md
Labels: bug

#712 Resolve several formatting issues with `currentdate`
  content/tutorials/themes/theme-objects/currentdate/index.md
Labels: bug

#715 Correct a few formatting issues and typo in `TEXT` theme object doc
  content/tutorials/themes/theme-objects/text/readme.md
Labels: enhancement
