Repository DNNCommunity/DNNDocs, pull requests merged in 2025-03, with the labels that each got.

#744 Multiple updates and fixed missing Obsolete attributes
  .github/workflows/Deploy.yml
  .github/workflows/PR_Validation.yml
  .nuke/build.schema.json
  build.ps1
  build.sh
  build/Build.cs
  build/_build.csproj
  docfx.json
  global.json
  templates/dnn-docs/partials/scripts.tmpl.partial
Labels: enhancement

#745 Updates string arguments in build
  build/Build.cs
Labels: build

#746 Additional attempt at fixing current build
  build/Build.cs
  global.json
Labels: build

#747 Fixed all plugins and more
  .gitignore
  .nuke/build.schema.json
  build/Build.cs
  build/Properties/launchSettings.json
  content/getting-started/contribution/dnn-docs/get-dnn-docs-running-locally/index.md
  docfx.json
  plugins/DNNCommunity.DNNDocs.Plugins/DNNCommunity.DNNDocs.Plugins.csproj
  plugins/DNNCommunity.DNNDocs.Plugins/MoreLinksBuildStep.cs
  plugins/DNNCommunity.DNNDocs.Plugins/MoreLinksProcessor.cs
  plugins/DNNCommunity.DNNDocs.Plugins/PageStatsBuildStep.cs
  plugins/DNNCommunity.DNNDocs.Plugins/PageStatsProcessor.cs
  plugins/DNNCommunity.DNNDocs.Plugins/Providers/GitHubApi.cs
  plugins/DNNCommunity.DNNDocs.Plugins/RepoStatsBuildStep.cs
  plugins/DNNCommunity.DNNDocs.Plugins/RepoStatsProcessor.cs
Labels: bug, build

#748 Commit latest build schema file
  .nuke/build.schema.json
Labels: bug, build

#749 Changed a wrong path with docfx js
  templates/dnn-docs/partials/scripts.tmpl.partial
Labels: bug, build

#750 Changed wrong key for github token
  content/getting-started/contribution/dnn-docs/get-dnn-docs-running-locally/index.md
  plugins/DNNCommunity.DNNDocs.Plugins/Providers/GitHubApi.cs
Labels: bug, build

#751 Changed font paths
  templates/dnn-docs/styles/docfx.vendor.css
Labels: bug

#753 Adds throtling to github API calls
  plugins/DNNCommunity.DNNDocs.Plugins/PageStatsBuildStep.cs
  plugins/DNNCommunity.DNNDocs.Plugins/Providers/GitHubApi.cs
Labels: bug

#757 Fixed selection of top/recent contributors
  build/Build.cs
  plugins/DNNCommunity.DNNDocs.Plugins/Providers/GitHubApi.cs
  plugins/DNNCommunity.DNNDocs.Plugins/RepoStatsBuildStep.cs
Labels: bug

#756 Update Suggested Upgrade Path
  content/getting-started/setup/upgrades/suggested-upgrade-path/index.md
Labels: documentation
